import type { Evidence, Incident } from "../types/legalDashboard";
import type {
  LegalReportBuildInput,
  LegalReportDocument,
  LegalReportSection,
  LegalReportTranscript,
} from "./legalReportTypes";

const fallback = "Not available";

function valueOrFallback(value?: string | number | boolean | null) {
  if (value === undefined || value === null || value === "") {
    return fallback;
  }

  return String(value);
}

function yesNo(value: boolean) {
  return value ? "Yes" : "No";
}

function findIncidentForEvidence(incidents: Incident[], evidenceId: string) {
  return incidents.find((incident) => incident.evidence.some((item) => item.id === evidenceId));
}

function uniqueIncidentsForEvidence(incidents: Incident[], selectedEvidence: Evidence[]) {
  const selectedEvidenceIds = new Set(selectedEvidence.map((item) => item.id));
  return incidents.filter((incident) =>
    incident.evidence.some((item) => selectedEvidenceIds.has(item.id))
  );
}

function mapTranscripts({ selectedEvidence, transcriptsByEvidenceId }: LegalReportBuildInput) {
  return selectedEvidence.map<LegalReportTranscript>((evidence) => {
    const transcript = transcriptsByEvidenceId[evidence.id];

    return {
      evidenceId: evidence.id,
      fileName: transcript?.fileName ?? evidence.filename,
      status: transcript?.status ?? "not_requested",
      text: transcript?.text?.trim() || "No completed transcript is attached to this evidence item.",
      requestedAt: transcript?.requestedAt ?? fallback,
      language: transcript?.language ?? fallback,
      languageProbability:
        typeof transcript?.languageProbability === "number"
          ? `${Math.round(transcript.languageProbability * 100)}%`
          : fallback,
    };
  });
}

export function buildLegalReportDocument(input: LegalReportBuildInput): LegalReportDocument {
  const { caseRecord, selectedEvidence, generatedAt = new Date(), warnings = [] } = input;
  const includedIncidents = uniqueIncidentsForEvidence(caseRecord.incidents, selectedEvidence);
  const transcripts = mapTranscripts(input);
  const generatedAtText = generatedAt.toLocaleString("en-GB", {
    dateStyle: "medium",
    timeStyle: "short",
  });
  const exportId = `EXPORT-${caseRecord.id}-${generatedAt.getTime()}`;
  const completedTranscriptCount = transcripts.filter((item) => item.status === "completed").length;

  const sections: LegalReportSection[] = [
    {
      title: "Disclaimer",
      paragraphs: [
        "This report package is generated from records available in the Nura legal dashboard at the time of generation. It is intended for controlled legal review and should be validated against the source system before formal submission.",
        "Missing fields are marked as not available. Transcript text is included only when a transcription result was completed during the report workflow.",
      ],
    },
    {
      title: "1. Case Information",
      rows: [
        ["Case ID", caseRecord.id],
        ["Export ID", exportId],
        ["Generated by", "Nura Legal Dashboard"],
        ["Case title", valueOrFallback(caseRecord.survivorAlias)],
        ["Linked victim", valueOrFallback(caseRecord.survivorAlias)],
        ["Report classification", "Confidential"],
        ["Status", valueOrFallback(caseRecord.status)],
        ["Created", valueOrFallback(caseRecord.createdAt)],
        ["Last updated", valueOrFallback(caseRecord.updatedAt)],
        ["Report generated", generatedAtText],
      ],
    },
    {
      title: "2. Case Overview",
      paragraphs: [
        `The package contains ${selectedEvidence.length} selected evidence item(s) across ${includedIncidents.length} incident(s).`,
        `Completed transcripts included: ${completedTranscriptCount}.`,
        "Evidence records were collected through the Nura application flow and are presented with available metadata, transcript text, and validation fields.",
      ],
    },
    {
      title: "3. Incident Overview",
      table: {
        headers: ["Incident ID", "Date and time", "Type", "Location", "Evidence"],
        rows: includedIncidents.map((incident) => [
          incident.id,
          valueOrFallback(incident.dateTime),
          valueOrFallback(incident.type),
          valueOrFallback(incident.location),
          String(incident.evidence.filter((item) => selectedEvidence.some((selected) => selected.id === item.id)).length),
        ]),
      },
      paragraphs:
        includedIncidents.length === 0
          ? ["No incidents are attached to the selected evidence."]
          : includedIncidents.map(
              (incident, index) =>
                `Incident ${index + 1}: ${valueOrFallback(incident.description)}`
            ),
    },
    {
      title: "4. Evidence Overview",
      table: {
        headers: ["Evidence ID", "Incident", "Type", "Filename", "Captured"],
        rows: selectedEvidence.map((evidence) => [
          evidence.id,
          findIncidentForEvidence(caseRecord.incidents, evidence.id)?.id ?? fallback,
          valueOrFallback(evidence.type),
          valueOrFallback(evidence.filename),
          valueOrFallback(evidence.capturedAt),
        ]),
      },
      paragraphs: selectedEvidence.length === 0 ? ["No evidence was selected for this package."] : undefined,
    },
    {
      title: "5. Transcript Information",
      paragraphs:
        transcripts.length === 0
          ? ["No evidence transcripts are attached to this package."]
          : transcripts.flatMap((transcript) => [
              `Evidence ${transcript.evidenceId} - ${transcript.fileName}`,
              `Status: ${transcript.status}; language: ${transcript.language}; confidence: ${transcript.languageProbability}; requested: ${transcript.requestedAt}`,
              transcript.text,
            ]),
    },
    {
      title: "6. Integrity & Validation",
      paragraphs: [
        "The report includes the available integrity indicators recorded for each selected evidence item.",
      ],
      table: {
        headers: ["Evidence ID", "Hash", "Timestamp", "Audit trail"],
        rows: selectedEvidence.map((evidence) => [
          evidence.id,
          yesNo(evidence.hashVerified),
          yesNo(evidence.timestampVerified),
          yesNo(evidence.auditTrailAvailable),
        ]),
      },
    },
    {
      title: "7. Audit Log",
      paragraphs: [
        ...warnings.map((warning) => `Warning: ${warning}`),
        warnings.length === 0 ? "No retrieval warnings were recorded during report generation." : "",
      ].filter(Boolean),
      table: {
        headers: ["Timestamp", "Action"],
        rows: [
          [generatedAtText, "Report generated"],
          [generatedAtText, `${selectedEvidence.length} evidence item(s) included`],
          [generatedAtText, `${completedTranscriptCount} completed transcript(s) included`],
        ],
      },
    },
    {
      title: "8. Report Sharing",
      paragraphs: [
        "Share this PDF only through approved legal or law-enforcement channels. Do not distribute raw evidence files with this report unless separately authorized.",
        "Recipients should verify the evidence identifiers and integrity fields against the source system before relying on the package.",
      ],
    },
    {
      title: "9. Conclusion",
      paragraphs: [
        "This package summarizes the selected case, incident, evidence, transcription, and integrity data available at generation time.",
        "Any missing or unavailable data should be reviewed in the Nura dashboard before external submission.",
      ],
    },
  ];

  return {
    title: `Legal Evidence Report - Case ${caseRecord.id}`,
    generatedAt: generatedAtText,
    caseRecord,
    selectedEvidence,
    includedIncidents,
    transcripts,
    sections,
    warnings,
  };
}
